#requires -Version 5.1
<#
.SYNOPSIS
Generates Claude Code configuration from the canonical VS Code/Copilot files.
.DESCRIPTION
Owns CLAUDE.md, .claude/skills/ and .claude/agents/ after the first run.
Regeneration replaces these outputs, including obsolete skills and agents.
Other .claude files, such as settings.local.json, are left untouched.
Agent frontmatter must use the repository's two-field format: a JSON-compatible
double-quoted description followed by an inline list of Copilot tool groups.
.EXAMPLE
.\generate-claude.ps1
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$sourceRoot = Join-Path $PSScriptRoot '.github'
$claudeRoot = Join-Path $PSScriptRoot '.claude'
$instructionsPath = Join-Path $PSScriptRoot 'CLAUDE.md'
$markerPath = Join-Path $claudeRoot '.generated-by-generate-claude'
$markerText = 'Generated by generate-claude.ps1. Edit the originals in .github, then regenerate.'
$encoding = New-Object System.Text.UTF8Encoding($false)
$toolMap = @{
    read = @('Read')
    search = @('Grep', 'Glob')
    edit = @('Edit', 'Write')
    execute = @('Bash', 'PowerShell')
    web = @('WebFetch', 'WebSearch')
}

$instructions = [System.IO.File]::ReadAllText((Join-Path $sourceRoot 'copilot-instructions.md'))
$skillsPath = Join-Path $sourceRoot 'skills'
$agentsPath = Join-Path $sourceRoot 'agents'
foreach ($sourcePath in @($skillsPath, $agentsPath)) {
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Container)) {
        throw "Missing source directory: $sourcePath"
    }
}

$agents = @{}
foreach ($agentFile in Get-ChildItem -LiteralPath $agentsPath -Filter '*.agent.md' -File) {
    $content = [System.IO.File]::ReadAllText($agentFile.FullName)
    $pattern = '\A---\r?\n description: [ \t]*(?<description>"(?:[^"\\\r\n]|\\.)*")[ \t]*\r?\n tools: [ \t]*\[(?<tools>[a-z, \t]+)\][ \t]*\r?\n---\r?\n(?<body>[\s\S]*)\z'
    $frontmatter = [regex]::Match($content, $pattern, [System.Text.RegularExpressions.RegexOptions]::IgnorePatternWhitespace)
    if (-not $frontmatter.Success) {
        throw "Unsupported agent frontmatter in $($agentFile.Name). Expected description and tools; see Get-Help .\generate-claude.ps1 -Full."
    }

    $description = $frontmatter.Groups['description'].Value
    $null = ConvertFrom-Json -InputObject $description
    $tools = @('Skill')
    foreach ($tool in $frontmatter.Groups['tools'].Value.Split(',')) {
        $toolName = $tool.Trim()
        if (-not $toolMap.ContainsKey($toolName)) {
            throw "Unsupported Copilot tool '$toolName' in $($agentFile.Name). Update the tool mapping first."
        }
        $tools += $toolMap[$toolName]
    }

    $name = $agentFile.Name -replace '\.agent\.md$', ''
    if ($name -cnotmatch '^[a-z][a-z0-9-]*$') {
        throw "Agent filename must use lowercase letters, digits and hyphens: $($agentFile.Name)"
    }
    $toolList = ($tools | Select-Object -Unique) -join ', '
    $agents["$name.md"] = "---`nname: $name`ndescription: $description`ntools: $toolList`n---`n`n<!-- $markerText -->`n" + $frontmatter.Groups['body'].Value
}

$outputs = @($instructionsPath, (Join-Path $claudeRoot 'skills'), (Join-Path $claudeRoot 'agents'))
if (Test-Path -LiteralPath $markerPath) {
    if ([System.IO.File]::ReadAllText($markerPath) -cne $markerText) {
        throw "Unrecognized generation marker: $markerPath"
    }
} else {
    foreach ($output in $outputs) {
        if (Test-Path -LiteralPath $output) {
            throw "Refusing to overwrite existing configuration: $output. Move it aside before generating."
        }
    }
}

foreach ($output in $outputs) {
    if (Test-Path -LiteralPath $output) {
        Remove-Item -LiteralPath $output -Recurse -Force
    }
}
$null = New-Item -ItemType Directory -Path $claudeRoot -Force
$null = New-Item -ItemType Directory -Path (Join-Path $claudeRoot 'agents') -Force
Copy-Item -LiteralPath $skillsPath -Destination (Join-Path $claudeRoot 'skills') -Recurse
[System.IO.File]::WriteAllText($instructionsPath, "<!-- $markerText -->`n`n$instructions", $encoding)
foreach ($name in $agents.Keys) {
    [System.IO.File]::WriteAllText((Join-Path $claudeRoot "agents/$name"), $agents[$name], $encoding)
}
[System.IO.File]::WriteAllText($markerPath, $markerText, $encoding)

Write-Host 'Generated CLAUDE.md, .claude/skills/ and .claude/agents/.'
Write-Host 'VS Code/Copilot remains the default. Edit .github originals and rerun this script after changes.'